This particluar method is a clustering method and this helps in clustering our data based on density, its a classification method in machine learning.

Two major inputs for the algorithm

    -   epsilon - This is just the radius created with the center point (our data point)
    -   Min Point - Default value for this is 3 in the algorithm and this suggests that there should be minimum of three data points inside of the circle that's created with the epsilon radius.
    -   As discussed above , if this minimum three point criteria is fulfilled here then the central point denoted over in the previous section will be called as a core point.

Boundary & Noise point

    -   Suppose a data point has only one core point as neighbor and not satisfying the requirement of minimum 3 points within it's circle , it will be called as a boundary point
    -   If a data point remains completely aloof and it's radius circle doesn't include any other core point or data point , then that particular data point will be called as noise point/outliers

In [12]:
#Lets try to apply dbscan on a created dataset
#importing the libraries
from sklearn.cluster import DBSCAN
import matplotlib.pyplot as plt
import numpy as np
 

In [13]:
# creating a numpy array
X = np.array([[1, 2], [2, 2], [2, 3],[8, 7], [8, 8], [25, 80]])

In [14]:
#applying dbscan on the data
clustering = DBSCAN(eps=3, min_samples=2).fit(X)
clustering.labels_

array([ 0,  0,  0,  1,  1, -1], dtype=int64)

The above cluster label signifies as below 

    -   The first three datapoints belong to cluster 0
    -   The fourth and fifth data points belong to cluster 1
    -   The sixth data point is a noise here hence it's output came in negative

Now we will see what can happen if we change the parameter value here. 

In [15]:
clustering = DBSCAN(eps=3, min_samples=9).fit(X)
clustering.labels_

array([-1, -1, -1, -1, -1, -1], dtype=int64)

We can see that by changing the minimum sample number as 9 every single data point went into noise. Let's understand what happened here.. our total data point here is 9. And by changing the sample number we are asking our algoritham to make one sample for eveyr single data point , hence every single item acted as outlier/Noise.

Now we will see what can happen if we change the epsilon value here

In [16]:
clustering = DBSCAN(eps=100, min_samples=3).fit(X)
clustering.labels_

array([0, 0, 0, 0, 0, 0], dtype=int64)